booktime/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

fonasa_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from django.views.generic import TemplateView, FormView
from main import views

urlpatterns = [
    path('about-us/', TemplateView.as_view(template_name='about.html'), name="about"),
    path('', TemplateView.as_view(template_name='home.html'), name="home"),
    path('contact-us', views.ContactUsView.as_view(), name="contact-us",),
    path('products', views.ProductList.as_view(), name="products",),
    path('signup', views.SignupView.as_view(), name="signup",),
]

main/models.py
from django.db import models

class ActiveManager(models.Model):
    def active(self):
        return self.filter(active=True)


class Producto(models.Model):
    name = models.CharField(max_length=32, help_text='Nombre del producto')
    description = models.TextField(blank=True,  help_text='Descripción del producto')
    price = models.DecimalField(max_digits=6, decimal_places=2,  help_text='precio del producto')
    active = models.BooleanField(default=True, help_text='Producto activo')
    date_update = models.DateTimeField(auto_now=True, help_text='Fecha de actualización del producto')

    objects = ActiveManager()

    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Products'
        ordering = ('pk',)

    def __str__(self):
        return self.name

class ProductImage(models.Model):
    product = models.ForeignKey(Producto, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="product-images")

class ProducTag(models.Model):
    products = models.ManyToManyField(Producto, blank=True)
    name = models.CharField(max_length=32)
    slug = models.SlugField(max_length=48)
    description = models.TextField(blank=True, null="")
    active = models.BooleanField(default=True)

main/forms.py
from django import forms
from django.core.mail import send_mail
from django.contrib.auth.forms import (UserCreationForm as DjangoUserCreationform)
from django.contrib.auth.models import User
from django.contrib.auth.forms import UsernameField

class ContactForm(forms.Form):
    name = forms.CharField(label='Your Name', max_length=100)
    message = forms.CharField(max_length=600, widget=forms.Textarea)

    def send_mail(self):
        message = "From:{0}\n{1}".format(
            self.cleaned_data["name"],
            self.cleaned_data["message"],
        )

        send_mail(
            "Site message",
            message,
            "site@mybooktime.cl",
            ["customer@mybooktime.cl"],
            fail_silently=False
        )

class UserCreationForm(DjangoUserCreationform):
    """
    Formulario de creación de usuario
    """
    class meta(DjangoUserCreationform.Meta):
        model = User
        fields = ("email",)
        field_classes = {"email":UsernameField}

    def send_mail(self):
        message = "Welcome {}".format(self.cleaned_data["email"])
        send_mail(
            "Welcome to BookTime",
            message,
            "site@mybooktime.cl",
            [self.cleaned_data["email"]],
            fail_silently=True
        )

main/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from main import forms
from main import models
from django.contrib.auth import login, authenticate
from django.contrib import messages
# Create your views here.

class SignupView(FormView):
    template_name = "signup.html"
    form_class = forms.UserCreationForm
    
    def get_success_url(self):
        redirect_to = self.request.GET.get("next", "/")
        return redirect_to

    def form_valid(self, form):
        response = super().form_valid(form)
        form.save()
        email = form.cleaned_data.get("email")
        raw_password = form.cleaned_data.get("password1")
        user = authenticate(email=email, password=raw_password)
        login(self.request, user)

        form.send.mail()
        messages.info(self.request, "Te has logueado correctamente")
        return response


def home(request):
    """
    Página de inicio

    """
    return (render(request, "home.html", {}))

class ContactUsView(FormView):
    """
    Formulario de contacto
    
    """
    template_name = "contact_form.html"
    form_class = forms.ContactForm
    success_url = "/"

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)

class ProductList(ListView):
    """
    Lista de productos
    
    """

    template_name = "product_list.html"

    def get_queryset(self):
        products = models.Producto.objects.all()
        return products.order_by("name")

main/templates/about.html
{% extends "base.html" %}

{% block content %}

<h2>About us</h2>
<p>BookTime is a new company</p>

{%  endblock content%}

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--Boostrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <title>BookTime</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">BookTime</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about-us/">About us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact-us' %}">Contact us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products' %}">Products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
                </li>
            </ul>
        </div>
    </nav>
<div class="container">
    {% block content %}

    {% endblock content %}
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!--Script Boostrap-->
   
</body>
</html>

main/templates/contact_form.html
{% extends "base.html" %}

{% block content %}

    <h2>Contact Us</h2>
    <p>Plese fill the form below to contact us.</p>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
                {{ form.name.label_tag }}
                <input type="text" name="name" id="id_name" 
                class="form-control {% if form.name.errors %} is-ivalid {% endif %}"
                placeholder="Your Name" value="{{ form.name.value | default:'' }}"
                >
                {% if form.name.errors %}
                <div class="invalid-feedback">
                    {{ form.name.errors }}
                </div>
                {% endif %}
        </div>
        <div class="form-group">
            {{ form.message.label_tag }}
            <textarea class="form-control" {% if form.message.errors %} is-invalid {% endif %}
                name="message" id="id_message"  rows="3">
                    {{ form.message.value | default:"" }}
            </textarea>
            {% if form.message.errors %}
                <div class="invalid-feedback">
                    {{ form.message.errors }}
                </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">
            Submit
        </button>
    </form>


{% endblock content %}

main/templates/home.html
{% extends "base.html" %}

{% block content %}

<h2>Home</h2>
<button class="btn btn-primary"> holi</button>

<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, tenetur
quaerat laboriosam facilis laudantium illum ad, amet explicabo aliquam 
placeat assumenda repudiandae odit ab. Pariatur earum accusantium
obcaecati minus aut!
</p>


{% endblock content %}

main/templates/product_list.html
{% extends 'base.html' %}
{% block content %}

    <h1>Products</h1>
    <ul class="list-group">
        {% for product in object_list %}
        <li class="list-group-item">
            <b><p>{{ product.name }}</p></b>
        </li>
    {% endfor %}
</ul>

{% endblock content %}

main/templates/signup.html
{% extends 'base.html' %}
{% block content %}

    <h1>Sign Up</h1>
    <p>
        Please fill the form below
    </p>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
                {{  form.email }}
                <input type="email" name="email" id="id_email"
                class="form-control" {% if form.email %} is-valid {% endif %}
                placeholder="Your Email" value="{{ form.email.value | default:'' }}"
                />
                {% if form.email.errors %}
                <div class="invalid-feedback">
                    {{ form.email.errors }}
                </div>
                {% endif %}
        </div>
        <div class="form-group">
            {{ form.password1 }}
            <input type="password" name="password1" id="id_password1"
            class="form-control" {% if form.password1.errors %} is-invalid {% endif %}
            value="{{ form.password1.value | default:'' }}"
            />
            {% if form.password.errors %}
            <div class="invalid-feedback">
                {{ form.password.errors }}
            </div>
            {% endif %}
        </div>
        <button type="submit" class="btn btn-primary">
            Submit
        </button>
    </form>
    
{% endblock content %}